"""Add citation style to articles

Revision ID: 3d6eb0804cdb
Revises: 3646dcd2a74b
Create Date: 2026-06-18 16:07:50.985795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6eb0804cdb'
down_revision = '3646dcd2a74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citation_style', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('citation_style')

    # ### end Alembic commands ###
